package codexoauth

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"net/url"
	"os/exec"
	"strings"
	"time"
)

const (
	clientID              = "app_EMoamEEZ73f0CkXaXp7hrann"
	authorizeURL          = "https://auth.openai.com/oauth/authorize"
	oauthExchangeEndpoint = "https://auth.openai.com/oauth/token"
	userinfoEndpoint      = "https://auth.openai.com/api/accounts/oauth/userinfo"
	usageEndpoint         = "https://chatgpt.com/backend-api/wham/usage"
	redirectURI           = "http://localhost:1455/auth/callback"
	scope                 = "openid profile email offline_access"
)

type Credentials struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresAt    int64  `json:"expiresAt"`
	AccountID    string `json:"accountId"`
	DisplayName  string `json:"displayName,omitempty"`
	PlanType     string `json:"planType,omitempty"`
}

type tokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

type callbackResult struct {
	code string
	err  error
}

func Login(ctx context.Context, onReturn func()) (Credentials, error) {
	verifier, err := randomString(32)
	if err != nil {
		return Credentials{}, fmt.Errorf("generate PKCE verifier: %w", err)
	}
	state, err := randomString(16)
	if err != nil {
		return Credentials{}, fmt.Errorf("generate OAuth state: %w", err)
	}
	returnToken, err := randomString(16)
	if err != nil {
		return Credentials{}, fmt.Errorf("generate OAuth return token: %w", err)
	}

	hash := sha256.Sum256([]byte(verifier))
	challenge := base64.RawURLEncoding.EncodeToString(hash[:])
	authorize, err := url.Parse(authorizeURL)
	if err != nil {
		return Credentials{}, fmt.Errorf("parse authorization URL: %w", err)
	}
	query := authorize.Query()
	query.Set("response_type", "code")
	query.Set("client_id", clientID)
	query.Set("redirect_uri", redirectURI)
	query.Set("scope", scope)
	query.Set("code_challenge", challenge)
	query.Set("code_challenge_method", "S256")
	query.Set("state", state)
	query.Set("id_token_add_organizations", "true")
	query.Set("codex_cli_simplified_flow", "true")
	query.Set("originator", "mux")
	authorize.RawQuery = query.Encode()

	resultCh := make(chan callbackResult, 1)
	returnCh := make(chan struct{}, 1)
	server := &http.Server{
		Addr:              "127.0.0.1:1455",
		ReadHeaderTimeout: 5 * time.Second,
	}
	server.Handler = callbackHandler(callbackConfig{
		expectedState: state,
		returnToken:   returnToken,
		onReturn:      onReturn,
	}, resultCh, returnCh)
	listenerErr := make(chan error, 1)
	listener, err := net.Listen("tcp", server.Addr)
	if err != nil {
		return Credentials{}, fmt.Errorf("start OAuth callback server: %w", err)
	}
	go func() { listenerErr <- server.Serve(listener) }()
	go func() {
		select {
		case <-returnCh:
		case <-ctx.Done():
		case <-time.After(2 * time.Minute):
		}
		if err := server.Close(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Printf("close OAuth callback server: %v", err)
		}
	}()

	//nolint:gosec // The URL is generated by the fixed OAuth endpoint and validated query parameters.
	if err := exec.CommandContext(ctx, "open", authorize.String()).Run(); err != nil {
		return Credentials{}, fmt.Errorf("open browser: %w", err)
	}

	select {
	case result := <-resultCh:
		if result.err != nil {
			return Credentials{}, result.err
		}
		return exchange(ctx, result.code, verifier)
	case err := <-listenerErr:
		if !errors.Is(err, http.ErrServerClosed) {
			return Credentials{}, fmt.Errorf("OAuth callback server: %w", err)
		}
		return Credentials{}, errors.New("OAuth callback server closed")
	case <-ctx.Done():
		return Credentials{}, ctx.Err()
	case <-time.After(5 * time.Minute):
		return Credentials{}, errors.New("OAuth login timed out")
	}
}

type callbackConfig struct {
	expectedState string
	returnToken   string
	onReturn      func()
}

func callbackHandler(config callbackConfig, resultCh chan<- callbackResult, returnCh chan<- struct{}) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("/auth/callback", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Query().Get("state") != config.expectedState {
			writePage(w, http.StatusBadRequest, "登录验证失败", "state 不匹配，请关闭此页面并重试。")
			resultCh <- callbackResult{err: errors.New("OAuth state mismatch")}
			return
		}
		code := r.URL.Query().Get("code")
		if code == "" {
			writePage(w, http.StatusBadRequest, "登录失败", "未收到授权码，请关闭此页面并重试。")
			resultCh <- callbackResult{err: errors.New("OAuth authorization code missing")}
			return
		}
		writeSuccessPage(w, config.returnToken)
		resultCh <- callbackResult{code: code}
	})
	mux.HandleFunc("/auth/return", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Query().Get("token") != config.returnToken {
			writePage(w, http.StatusForbidden, "返回失败", "返回凭据无效，请重新登录。")
			return
		}
		writePage(w, http.StatusOK, "返回成功", "已返回 Mux 桌面程序，可以关闭此页面。")
		if config.onReturn != nil {
			config.onReturn()
		}
		returnCh <- struct{}{}
	})
	mux.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) {
		writePage(w, http.StatusNotFound, "页面不存在", "请返回应用重试。")
	})
	return mux
}

type UserProfile struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	Avatar string `json:"picture"`
}

type UsageWindow struct {
	UsedPercent        float64 `json:"used_percent"`
	LimitWindowSeconds int64   `json:"limit_window_seconds"`
	ResetAt            int64   `json:"reset_at"`
}

type UsageRateLimit struct {
	PrimaryWindow   *UsageWindow `json:"primary_window"`
	SecondaryWindow *UsageWindow `json:"secondary_window"`
	LimitReached    bool         `json:"limit_reached"`
}

type UsageCredits struct {
	HasCredits bool   `json:"has_credits"`
	Unlimited  bool   `json:"unlimited"`
	Balance    string `json:"balance"`
}

type Usage struct {
	PlanType  string          `json:"plan_type"`
	RateLimit *UsageRateLimit `json:"rate_limit"`
	Credits   *UsageCredits   `json:"credits"`
}

func UsageInfo(ctx context.Context, accessToken, accountID string) (Usage, error) {
	if accessToken == "" || accountID == "" {
		return Usage{}, errors.New("access token and account ID are required")
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, usageEndpoint, nil)
	if err != nil {
		return Usage{}, fmt.Errorf("create usage request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+accessToken)
	req.Header.Set("ChatGPT-Account-ID", accountID)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return Usage{}, fmt.Errorf("request usage: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return Usage{}, fmt.Errorf("read usage response: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return Usage{}, fmt.Errorf("usage request failed (%s)", resp.Status)
	}
	var usage Usage
	if err := json.Unmarshal(body, &usage); err != nil {
		return Usage{}, fmt.Errorf("decode usage response: %w", err)
	}
	return usage, nil
}

func UserInfo(ctx context.Context, accessToken string) (UserProfile, error) {
	if accessToken == "" {
		return UserProfile{}, errors.New("access token is empty")
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, userinfoEndpoint, nil)
	if err != nil {
		return UserProfile{}, fmt.Errorf("create userinfo request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+accessToken)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return UserProfile{}, fmt.Errorf("request userinfo: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return UserProfile{}, fmt.Errorf("read userinfo response: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return UserProfile{}, fmt.Errorf("userinfo request failed (%s)", resp.Status)
	}
	var info UserProfile
	if err := json.Unmarshal(body, &info); err != nil {
		return UserProfile{}, fmt.Errorf("decode userinfo response: %w", err)
	}
	if info.Name == "" && info.Email == "" {
		return UserProfile{}, errors.New("userinfo response contains no name or email")
	}
	return info, nil
}

func exchange(ctx context.Context, code, verifier string) (Credentials, error) {
	form := url.Values{}
	form.Set("grant_type", "authorization_code")
	form.Set("client_id", clientID)
	form.Set("code", code)
	form.Set("code_verifier", verifier)
	form.Set("redirect_uri", redirectURI)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, oauthExchangeEndpoint, strings.NewReader(form.Encode()))
	if err != nil {
		return Credentials{}, fmt.Errorf("create token request: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return Credentials{}, fmt.Errorf("exchange authorization code: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return Credentials{}, fmt.Errorf("read token response: %w", err)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return Credentials{}, fmt.Errorf("token exchange failed (%s)", resp.Status)
	}
	var token tokenResponse
	if err := json.Unmarshal(body, &token); err != nil {
		return Credentials{}, fmt.Errorf("decode token response: %w", err)
	}
	if token.AccessToken == "" || token.RefreshToken == "" || token.ExpiresIn <= 0 {
		return Credentials{}, errors.New("token response missing required fields")
	}
	accountID, displayName, planType, err := claimsFromJWT(token.AccessToken)
	if err != nil {
		return Credentials{}, err
	}
	return Credentials{
		AccessToken: token.AccessToken, RefreshToken: token.RefreshToken,
		ExpiresAt: time.Now().Add(time.Duration(token.ExpiresIn) * time.Second).UnixMilli(),
		AccountID: accountID, DisplayName: displayName, PlanType: planType,
	}, nil
}

func PlanTypeFromAccessToken(token string) (string, error) {
	_, _, planType, err := claimsFromJWT(token)
	return planType, err
}

func claimsFromJWT(token string) (string, string, string, error) {
	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		return "", "", "", errors.New("invalid access token")
	}
	payload, err := base64.RawURLEncoding.DecodeString(parts[1])
	if err != nil {
		return "", "", "", fmt.Errorf("decode access token: %w", err)
	}
	var claims map[string]json.RawMessage
	if err := json.Unmarshal(payload, &claims); err != nil {
		return "", "", "", fmt.Errorf("decode access token claims: %w", err)
	}
	var auth struct {
		AccountID string `json:"chatgpt_account_id"`
		PlanType  string `json:"chatgpt_plan_type"`
	}
	raw, ok := claims["https://api.openai.com/auth"]
	if !ok || json.Unmarshal(raw, &auth) != nil || auth.AccountID == "" {
		return "", "", "", errors.New("access token does not contain ChatGPT account ID")
	}
	var displayName string
	var planType string
	for _, key := range []string{"name", "preferred_username", "email"} {
		if raw, ok := claims[key]; ok && json.Unmarshal(raw, &displayName) == nil && displayName != "" {
			break
		}
	}
	if raw, ok := claims["chatgpt_plan_type"]; ok {
		_ = json.Unmarshal(raw, &planType)
	}
	if planType == "" {
		planType = auth.PlanType
	}
	return auth.AccountID, displayName, planType, nil
}

func randomString(size int) (string, error) {
	buf := make([]byte, size)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

func writeSuccessPage(w http.ResponseWriter, returnToken string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	_, _ = fmt.Fprintf(w, `<!doctype html>
<html lang="zh-CN">
<head><meta charset="utf-8"><title>登录成功</title></head>
<body>
  <h1>登录成功</h1>
  <p>已完成登录，请返回 Mux 桌面程序。账号状态会自动更新。</p>
  <button type="button" onclick="window.location.href='/auth/return?token=%s'">返回 Mux</button>
</body>
</html>`, returnToken)
}

func writePage(w http.ResponseWriter, status int, title, message string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(status)
	_, _ = fmt.Fprintf(w, "<!doctype html><meta charset=\"utf-8\"><title>%s</title><h1>%s</h1><p>%s</p>", title, title, message)
}
