// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function CancelLogin(arg1) {
  return window['go']['main']['App']['CancelLogin'](arg1);
}

export function ConfigureFinchGateway() {
  return window['go']['main']['App']['ConfigureFinchGateway']();
}

export function GetGatewayPort() {
  return window['go']['main']['App']['GetGatewayPort']();
}

export function GetSyncInterval() {
  return window['go']['main']['App']['GetSyncInterval']();
}

export function IsGatewayRunning() {
  return window['go']['main']['App']['IsGatewayRunning']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function LoginAccount(arg1) {
  return window['go']['main']['App']['LoginAccount'](arg1);
}

export function OpenConfigFileFolder() {
  return window['go']['main']['App']['OpenConfigFileFolder']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function SetGatewayPort(arg1) {
  return window['go']['main']['App']['SetGatewayPort'](arg1);
}

export function SetSyncInterval(arg1) {
  return window['go']['main']['App']['SetSyncInterval'](arg1);
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
