// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function CancelLogin(arg1) {
  return window['go']['main']['App']['CancelLogin'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function LoginAccount(arg1) {
  return window['go']['main']['App']['LoginAccount'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
