// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:string):Promise<main.AccountView>;

export function CancelLogin(arg1:string):Promise<void>;

export function ConfigureFinchGateway():Promise<void>;

export function GetGatewayPort():Promise<number>;

export function GetSyncInterval():Promise<number>;

export function IsGatewayRunning():Promise<boolean>;

export function ListAccounts():Promise<Array<main.AccountView>>;

export function LoginAccount(arg1:string):Promise<void>;

export function OpenConfigFileFolder():Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function SetGatewayPort(arg1:number):Promise<void>;

export function SetSyncInterval(arg1:number):Promise<void>;

export function StartGateway():Promise<void>;

export function StopGateway():Promise<void>;

export function UpdateAccount(arg1:string):Promise<void>;
