// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:string):Promise<main.AccountView>;

export function ListAccounts():Promise<Array<main.AccountView>>;

export function LoginAccount(arg1:string):Promise<void>;

export function RemoveAccount(arg1:string):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;
